# Generated by Django 3.1 on 2020-09-27 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200919_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
