# Generated by Django 3.1 on 2020-09-27 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_community_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='key',
            field=models.UUIDField(default=uuid.uuid1, editable=False, null=True, unique=True),
        ),
    ]
