# Generated by Django 3.1 on 2020-09-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200927_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='key',
            field=models.UUIDField(default='BYGYsJGGt6we7ZWRLkwSqq', editable=False, null=True, unique=True),
        ),
    ]
