# Generated by Django 3.1 on 2020-09-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20200927_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='key',
            field=models.CharField(editable=False, max_length=500, null=True, unique=True),
        ),
    ]
