# Generated by Django 3.1 on 2020-10-04 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0008_auto_20200927_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityowner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
