# Generated by Django 3.1 on 2020-08-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityowner'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.communityowner', verbose_name='event creator'),
        ),
    ]
