# Generated by Django 3.1 on 2020-09-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200823_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='postion',
            new_name='position',
        ),
    ]
