# Generated by Django 3.1 on 2020-09-28 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0005_auto_20200927_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='event creator'),
        ),
    ]
