# Generated by Django 3.1 on 2020-09-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20200927_2109'),
        ('event', '0006_auto_20200928_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.communityowner', verbose_name='event creator'),
        ),
    ]
