# Generated by Django 3.1 on 2020-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200928_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_at',
            field=models.DateField(null=True, verbose_name='event ending date'),
        ),
    ]
