# Generated by Django 3.1 on 2020-08-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
